# Generated by Django 3.2.13 on 2022-05-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tugas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_tugas', models.CharField(max_length=50, verbose_name='Judul Tugas')),
                ('deskripsi_tugas', models.CharField(max_length=100, verbose_name='Deskripsi Tugas')),
                ('input_file', models.FileField(upload_to='', verbose_name='File')),
            ],
        ),
    ]
