# Generated by Django 3.2.13 on 2022-05-21 14:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ustad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tugas',
            name='batas_waktu',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Batas Waktu'),
            preserve_default=False,
        ),
    ]
