# Generated by Django 3.2.13 on 2022-05-21 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ustad', '0002_tugas_batas_waktu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tugas',
            name='batas_waktu',
            field=models.DateField(verbose_name='Batas Waktu'),
        ),
    ]
